#! /bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "1" "2" "3" "4" "5" "6" "7" "8" "9" 

bspc config border_width         2
bspc config normal_border_color  "#282828"
bspc config focused_border_color "#d3869b"
bspc config active_border_color  "#d3869b"
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false 
bspc config gapless_monocle      false 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
